### PR TITLE
Add jumping ahead and back in video

### PR DESCRIPTION
**Pull request by fluks**
Jumping only works when the video element has focus, you need to press the video element with a mouse button.

### CODE REVIEW

**Comment by fluks** [comment]
Implements #4.

**Comment by fluks** [comment]
Btw, I'm participating in Hacktoberfest. Could you be so kind and add either hacktoberfest topic to your repo or hacktoberfest-approved label to my PRs you accept?

**Comment by lunaazumi** [comment]
@fluks quick note that the `target` object is not related to the fallback (replaced) player. It is handled by 2 video element, with ID prefix `FRP`. Anyways, thanks for the code. I am quite new to JS. I have also added the hacktoberfest tag to the repo as you have requested. For now I only have to merge the PR and it's all done?

**Comment by fluks** [comment]
Okay. I didn't read all the code, only parts I thought were relevant to implement this functionality. Does the jumping work for you? And should I add the jumping also to the #FRP-fallbackVideo element? I can do that before you merge.

Yes, nothing else is required from you, the tag is enough. Thank you.

**Comment by lunaazumi** [comment]
I couldn't test right now. For now, it is still lacking the audio sync. Thanks for the codebase. Have a great day!

**Comment by fluks** [comment]
The audio jumps too when I test.

**Comment by lunaazumi** [comment]
@fluks I had just tested and it actually works. Thanks so much! May I implement your code for the audio too?

**Comment by fluks** [comment]
Yes, of course you can.

**Pull request merged**
